In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)


/var/folders/mx/rxqrr3wj24q81gylcgl4fjvh0000gn/T/ipykernel_78270/2870173724.py:8: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [2]:
fbs = pd.read_excel('./list_fbs.xlsx')

In [3]:
fbs.head()

Unnamed: 0  id_uni   id_fak  \
0  0.0         2       30546     
1  1.0         2       1200001   
2  2.0         2       420102    
3  3.0         2       600799    
4  4.0         2       200001    

                                                                     name_fb  \
0  Philologische Fakultät an der Uni Freiburg                                  
1  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       
2  Fakultät für Biologie an der Uni Freiburg                                   
3  Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg   
4  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       

       city                 street_nr    plz     total_doz total_stud  \
0  Freiburg  Rempartstraße 15          79085  keine Angabe  470 *       
1  Freiburg  Albertstr. 21             79104  NaN           90          
2  Freiburg  Schänzlestraße 1          79104  NaN           1.260       
3  Freiburg  Platz der Alten Synagoge  79098  NaN           530 *       
4  Freiburg  Albertstr. 21             79104  NaN           940         

  total_stud_ma  support_start tframe_grad_ba tframe_grad_ma       lon  \
0  130 *         keine Angaben  73,3 % *       26,7 % *       7.847936   
1  NaN           Nur Master SG  keine Angaben  53,7 %         7.847936   
2  NaN           11/14 Punkten  88,2 %         54,9 %         7.847936   
3  160 *         keine Angaben  83,1 % *       43,5 % *       7.847936   
4  NaN           7/14 Punkten   78,9 %         NaN            7.847936   

         lat                       int_ba                       int_ma  \
0  47.998253  Indikator nicht ausgewiesen  Indikator nicht ausgewiesen   
1  47.998253  NaN                          NaN                           
2  47.998253  NaN                          NaN                           
3  47.998253  NaN                          NaN                           
4  47.998253  NaN                          NaN                           

    foreign_spot                   sup_doz  \
0  keine Angaben  keine Befragung            
1  NaN            Unterstützung im Studium   
2  NaN            2,4                        
3  keine Angabe   NaN                        
4  NaN            NaN                        

                         sup_in_studies           curriculum  \
0  keine Befragung                       keine Befragung       
1  NaN                                   Studienorganisation   
2  Ranggruppe nicht eindeutig zuweisbar  2,5                   
3  Lehrangebot                           NaN                   
4  Fallzahl kleiner 15                   NaN                   

         students_orga            exams                    research_conn  \
0  keine Befragung      keine Befragung  keine Befragung                   
1  NaN                  Laborpraktika    Angebote zur Berufsorientierung   
2  1,6 *                2,4              2,1                               
3  Prüfungen            NaN              Angebote zur Berufsorientierung   
4  Fallzahl kleiner 15  NaN              NaN                               

                   offer_joborientation    supp_exchange        faculties  \
0  keine Befragung                       keine Befragung  keine Befragung   
1  NaN                                   Räume            NaN               
2  Ranggruppe nicht eindeutig zuweisbar  2,4              1,7               
3  NaN                                   Räume            NaN               
4  NaN                                   NaN              NaN               

                bib it_infrastructure                        grade_overall  \
0  keine Befragung   keine Befragung   keine Befragung                       
1  IT-Infrastruktur  NaN               Weitere Studiengänge am Fachbereich   
2  1,8 *             2,3 *             2,2                                   
3  IT-Infrastruktur  NaN               Betreuung durch Lehrende              
4  NaN          

In [4]:
fbs.drop(labels = 'Unnamed: 0', axis = 1, inplace = True)

In [5]:
#studis['name_stud'] = studis['name_stud'].apply(lambda x: x.title())
#studis.head()

In [6]:
fbs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2251 entries, 0 to 2250
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id_uni                2251 non-null   int64  
 1   id_fak                2251 non-null   int64  
 2   name_fb               2251 non-null   object 
 3   city                  2251 non-null   object 
 4   street_nr             2250 non-null   object 
 5   plz                   2251 non-null   int64  
 6   total_doz             282 non-null    object 
 7   total_stud            1747 non-null   object 
 8   total_stud_ma         1080 non-null   object 
 9   support_start         1994 non-null   object 
 10  tframe_grad_ba        1554 non-null   object 
 11  tframe_grad_ma        1421 non-null   object 
 12  lon                   2251 non-null   float64
 13  lat                   2251 non-null   float64
 14  int_ba                702 non-null    object 
 15  int_ma               

In [7]:
fbs.drop('total_doz', axis = 1, inplace = True)


In [8]:
fbs[fbs['total_stud']=='Anzahl Masterstudierende']

id_uni  id_fak  \
1779  468     604155   
1811  478     491021   

                                                               name_fb  \
1779  Fakultät für Ingenieurwissenschaften an der HS Wismar              
1811  Fachbereich Bauwesen und Geoinformation an der Jade HS/Oldenburg   

           city                 street_nr    plz                total_stud  \
1779  Wismar     Philipp-Müller-Straße 14  23966  Anzahl Masterstudierende   
1811  Oldenburg  Ofener Straße 16          26121  Anzahl Masterstudierende   

     total_stud_ma              support_start tframe_grad_ba tframe_grad_ma  \
1779  NaN           es liegen keine Daten vor  keine Angaben  keine Angaben   
1811  NaN           es liegen keine Daten vor  keine Angaben  keine Angaben   

            lon        lat int_ba int_ma foreign_spot  \
1779  11.440575  53.889339  NaN    NaN    NaN           
1811  8.201775   53.141610  NaN    NaN    NaN           

                       sup_doz sup_in_studies           curriculum  \
1779  Unterstützung im Studium  Lehrangebot    Studienorganisation   
1811  Unterstützung im Studium  Lehrangebot    Studienorganisation   

     students_orga exams research_conn offer_joborientation supp_exchange  \
1779  Prüfungen     NaN   NaN           Praxisbezug          Räume          
1811  Prüfungen     NaN   NaN           Praxisbezug          Räume          

     faculties               bib it_infrastructure grade_overall  \
1779  NaN       IT-Infrastruktur  NaN               NaN            
1811  NaN       IT-Infrastruktur  NaN               NaN            

     total_students_la la_studies  
1779  NaN               NaN        
1811  NaN               NaN

In [9]:
def to_num_or_null(x):
    try:
        return pd.to_numeric(x)
    except:
        return np.nan

In [10]:
fbs['total_stud'] = fbs['total_stud'].apply(lambda x : to_num_or_null(str(x).replace(" *", "").replace('.','')))

In [11]:
fbs['total_stud'].head(50)

0     470.0 
1     90.0  
2     1260.0
3     530.0 
4     940.0 
5     190.0 
6     330.0 
7     230.0 
8     420.0 
9     1000.0
10   NaN    
11    2500.0
12    530.0 
13    3080.0
14    170.0 
15    720.0 
16    500.0 
17    570.0 
18    730.0 
19    440.0 
20    430.0 
21    1620.0
22    590.0 
23    420.0 
24    180.0 
25    1770.0
26    1030.0
27    320.0 
28    930.0 
29    170.0 
30    250.0 
31    850.0 
32    780.0 
33    2790.0
34    1050.0
35    3560.0
36    780.0 
37    2550.0
38    1030.0
39    880.0 
40    130.0 
41    530.0 
42    1210.0
43    560.0 
44    450.0 
45   NaN    
46   NaN    
47   NaN    
48   NaN    
49    270.0 
Name: total_stud, dtype: float64

In [12]:
fbs["total_stud"] =fbs["total_stud"].convert_dtypes(int)

In [13]:
fbs['total_stud_ma'] = fbs['total_stud_ma'].apply(lambda x : to_num_or_null(str(x).replace(" *", "").replace('.','')))

In [14]:
fbs["total_stud_ma"] =fbs["total_stud_ma"].convert_dtypes(int)
fbs['total_stud_ma'].isnull()

0       False
1       True 
2       True 
3       False
4       True 
5       False
6       True 
7       True 
8       False
9       False
10      True 
11      True 
12      False
13      True 
14      True 
15      True 
16      False
17      True 
18      False
19      False
20      True 
21      False
22      True 
23      False
24      True 
25      True 
26      True 
27      False
28      True 
29      True 
30      False
31      False
32      False
33      True 
34      False
35      True 
36      True 
37      False
38      True 
39      False
40      False
41      True 
42      False
43      True 
44      True 
45      True 
46      False
47      True 
48      False
49      False
50      False
51      False
52      True 
53      True 
54      True 
55      True 
56      True 
57      True 
58      False
59      True 
60      True 
61      False
62      False
63      True 
64      True 
65      False
66      False
67      False
68      True 
69      True 
70      True 
71    

In [15]:
fbs.head()

id_uni   id_fak  \
0  2       30546     
1  2       1200001   
2  2       420102    
3  2       600799    
4  2       200001    

                                                                     name_fb  \
0  Philologische Fakultät an der Uni Freiburg                                  
1  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       
2  Fakultät für Biologie an der Uni Freiburg                                   
3  Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg   
4  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       

       city                 street_nr    plz  total_stud  total_stud_ma  \
0  Freiburg  Rempartstraße 15          79085  470         130             
1  Freiburg  Albertstr. 21             79104  90          <NA>            
2  Freiburg  Schänzlestraße 1          79104  1260        <NA>            
3  Freiburg  Platz der Alten Synagoge  79098  530         160             
4  Freiburg  Albertstr. 21             79104  940         <NA>            

   support_start tframe_grad_ba tframe_grad_ma       lon        lat  \
0  keine Angaben  73,3 % *       26,7 % *       7.847936  47.998253   
1  Nur Master SG  keine Angaben  53,7 %         7.847936  47.998253   
2  11/14 Punkten  88,2 %         54,9 %         7.847936  47.998253   
3  keine Angaben  83,1 % *       43,5 % *       7.847936  47.998253   
4  7/14 Punkten   78,9 %         NaN            7.847936  47.998253   

                        int_ba                       int_ma   foreign_spot  \
0  Indikator nicht ausgewiesen  Indikator nicht ausgewiesen  keine Angaben   
1  NaN                          NaN                          NaN             
2  NaN                          NaN                          NaN             
3  NaN                          NaN                          keine Angabe    
4  NaN                          NaN                          NaN             

                    sup_doz                        sup_in_studies  \
0  keine Befragung           keine Befragung                        
1  Unterstützung im Studium  NaN                                    
2  2,4                       Ranggruppe nicht eindeutig zuweisbar   
3  NaN                       Lehrangebot                            
4  NaN                       Fallzahl kleiner 15                    

            curriculum        students_orga            exams  \
0  keine Befragung      keine Befragung      keine Befragung   
1  Studienorganisation  NaN                  Laborpraktika     
2  2,5                  1,6 *                2,4               
3  NaN                  Prüfungen            NaN               
4  NaN                  Fallzahl kleiner 15  NaN               

                     research_conn                  offer_joborientation  \
0  keine Befragung                  keine Befragung                        
1  Angebote zur Berufsorientierung  NaN                                    
2  2,1                              Ranggruppe nicht eindeutig zuweisbar   
3  Angebote zur Berufsorientierung  NaN                                    
4  NaN                              NaN                                    

     supp_exchange        faculties               bib it_infrastructure  \
0  keine Befragung  keine Befragung  keine Befragung   keine Befragung    
1  Räume            NaN              IT-Infrastruktur  NaN                
2  2,4              1,7              1,8 *             2,3 *              
3  Räume            NaN              IT-Infrastruktur  NaN                
4  NaN              NaN              NaN               NaN                

                         grade_overall total_students_la  \
0  keine Befragung                      330 *              
1  Weitere Studiengänge am Fachbereich  NaN                
2  2,2                                  263                
3  Betreuung durch Lehrende             NaN                
4  2,5                            

In [16]:

def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = (float(x.split('/')[0]))/float((x.split('/')[1]))
        return x
    except:
        return np.nan
    
fbs['support_start'] = fbs['support_start'].apply(lambda x: clean_sup(str(x)))
fbs['support_start'].unique()

array([       nan, 0.78571429, 0.5       , 0.71428571, 0.64285714,
       0.66666667, 0.84615385, 0.28571429, 0.85714286, 0.92857143,
       0.42857143, 0.35714286, 0.75      , 0.83333333, 0.57142857,
       0.58333333, 0.41666667, 1.        , 0.92307692, 0.25      ,
       0.53846154, 0.76923077, 0.46153846, 0.91666667, 0.61538462,
       0.33333333, 0.38461538, 0.69230769, 0.21428571])

In [17]:
clean_sup('12/14 asd')

0.8571428571428571

In [18]:
fbs['tframe_grad_ba'].unique()

array(['73,3 % *', 'keine Angaben', '88,2 %', '83,1 % *', '78,9 %',
       '98,7 %', '73,9 %', '95,3 %', '83,8 %', '54,5 %', nan, '89,4 %',
       '89,5 % *', '92,3 % *', '56,9 %', '92,4 %', '79,7 % *', '79,3 %',
       '81,5 % *', '94,3 %', '49,4 % *', '96,1 % *', '70,1 %', '97,7 %',
       '92,2 %', '57,6 %', '78,5 %', '<10 Absolventen / Jahr', '62,1 %',
       '69,0 %', '36,0 %', '72,6 %', '85,4 % *', '81,8 %', '82,3 %',
       '83,0 %', '89,3 %',
       'nicht durchgängig 10 Absolventen/Jahr im Beobachtungszeitraum; Quelle: Fachbereichsbefragung',
       '88,4 %', '69,0 % *', '89,0 % *', '77,5 % *', '76,8 % *', '95,1 %',
       '91,5 %', '93,6 %',
       'nicht ausgewiesen da weniger 10 Absolventen/Jahr. Quelle: Statistisches Bundesamt',
       '68,0 % *', '73,6 %', '60,0 %', '58,7 %', '79,1 %', '78,7 %',
       '68,5 %', '53,4 %',
       'im Beobachtungszeitraum noch keine Absolventen', '76,2 % *',
       '79,6 %', '92,7 %', '88,1 %', '68,8 %', 'noch keine Absolventen',
       '69

In [19]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))/100
        return x
    except:
        return np.nan
    
fbs['tframe_grad_ba'] = fbs['tframe_grad_ba'].apply(lambda x: clean_sup(str(x)))
fbs['tframe_grad_ba'].unique()



array([0.733,   nan, 0.882, 0.831, 0.789, 0.987, 0.739, 0.953, 0.838,
       0.545, 0.894, 0.895, 0.923, 0.569, 0.924, 0.797, 0.793, 0.815,
       0.943, 0.494, 0.961, 0.701, 0.977, 0.922, 0.576, 0.785, 0.621,
       0.69 , 0.36 , 0.726, 0.854, 0.818, 0.823, 0.83 , 0.893, 0.884,
       0.89 , 0.775, 0.768, 0.951, 0.915, 0.936, 0.68 , 0.736, 0.6  ,
       0.587, 0.791, 0.787, 0.685, 0.534, 0.762, 0.796, 0.927, 0.881,
       0.688, 0.692, 0.869, 0.891, 0.973, 0.849, 0.544, 0.801, 0.714,
       0.832, 0.934, 0.84 , 0.904, 0.933, 0.646, 0.803, 0.781, 0.728,
       0.741, 0.721, 0.39 , 0.475, 0.75 , 0.853, 0.663, 0.765, 0.659,
       0.574, 0.989, 0.707, 0.865, 0.876, 0.67 , 0.706, 0.511, 0.928,
       0.848, 0.675, 0.798, 0.969, 0.558, 0.983, 0.861, 0.847, 0.481,
       0.614, 0.906, 0.656, 0.682, 0.959, 0.962, 0.541, 0.64 , 0.758,
       0.86 , 0.364, 0.724, 1.   , 0.878, 0.902, 0.353, 0.867, 0.852,
       0.944, 0.925, 0.638, 0.744, 0.642, 0.774, 0.837, 0.806, 0.949,
       0.786, 0.605,

In [20]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))/100
        return x
    except:
        return np.nan
    
fbs['tframe_grad_ma'] = fbs['tframe_grad_ma'].apply(lambda x: clean_sup(str(x)))
fbs['tframe_grad_ma'].unique()

array([0.267, 0.537, 0.549, 0.435,   nan, 0.676, 0.109, 0.32 , 0.136,
       0.213, 0.295, 0.63 , 0.85 , 0.154, 0.237, 0.509, 0.329, 0.153,
       0.548, 0.766, 0.473, 0.402, 0.532, 0.778, 0.759, 0.714, 0.364,
       0.583, 0.651, 0.914, 0.645, 0.67 , 0.677, 0.333, 0.193, 0.207,
       0.299, 0.426, 0.49 , 0.348, 0.861, 0.493, 0.116, 0.597, 0.771,
       0.692, 0.565, 0.882, 0.46 , 0.798, 0.905, 0.788, 0.874, 0.737,
       0.921, 0.681, 0.427, 0.588, 0.526, 0.227, 0.508, 0.388, 0.456,
       0.595, 0.308, 0.667, 0.397, 0.593, 0.898, 0.807, 0.385, 0.206,
       0.352, 0.478, 0.462, 0.414, 0.811, 0.345, 0.833, 0.683, 0.38 ,
       0.551, 0.542, 0.75 , 0.638, 0.649, 1.   , 0.717, 0.29 , 0.313,
       0.494, 0.297, 0.111, 0.511, 0.962, 0.612, 0.465, 0.268, 0.459,
       0.371, 0.429, 0.606, 0.281, 0.786, 0.433, 0.452, 0.381, 0.127,
       0.408, 0.265, 0.4  , 0.594, 0.636, 0.531, 0.937, 0.422, 0.475,
       0.89 , 0.796, 0.34 , 0.838, 0.222, 0.42 , 0.57 , 0.528, 0.907,
       0.904, 0.492,

In [21]:
fbs['int_ba'].unique()

array(['Indikator nicht ausgewiesen', nan, '3/9 Punkten', '2/9 Punkten',
       '5/9 Punkten', '4/13 Punkten', '4/10 Punkten', '4/9 Punkten',
       '3/10 Punkten', '1/9 Punkten', '6/9 Punkten', '7/13 Punkten',
       '6/13 Punkten', '8/9 Punkten', '8/13 Punkten', '7/9 Punkten',
       'kein entsprechender Bachelorstudiengang', '5/13 Punkten',
       '5/10 Punkten', 'Internationale Ausrichtung, Master',
       '9/13 Punkten', '2/10 Punkten', '8/10 Punkten', '3/13 Punkten',
       'kein Bachelorstudiengang', '6/10 Punkten', '10/13 Punkten',
       '2/13 Punkten', '7/10 Punkten', '8/12 Punkten', '3/12 Punkten',
       '7/12 Punkten', '6/12 Punkten', '9/12 Punkten', '5/12 Punkten',
       '10/12 Punkten', '1/10 Punkten', '4/12 Punkten', '1/13 Punkten',
       '0/10 Punkten'], dtype=object)

In [22]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = (float(x.split('/')[0]))/float((x.split('/')[1]))
        return x
    except:
        return np.nan
fbs['int_ba'] = fbs['int_ba'].apply(lambda x: clean_sup(str(x)))
fbs['int_ba'].unique()

array([       nan, 0.33333333, 0.22222222, 0.55555556, 0.30769231,
       0.4       , 0.44444444, 0.3       , 0.11111111, 0.66666667,
       0.53846154, 0.46153846, 0.88888889, 0.61538462, 0.77777778,
       0.38461538, 0.5       , 0.69230769, 0.2       , 0.8       ,
       0.23076923, 0.6       , 0.76923077, 0.15384615, 0.7       ,
       0.25      , 0.58333333, 0.75      , 0.41666667, 0.83333333,
       0.1       , 0.07692308, 0.        ])

In [23]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = (float(x.split('/')[0]))/float((x.split('/')[1]))
        return x
    except:
        return np.nan
fbs['int_ma'] = fbs['int_ma'].apply(lambda x: clean_sup(str(x)))
fbs['int_ma'].unique()

array([       nan, 0.44444444, 0.66666667, 0.55555556, 0.22222222,
       0.46153846, 0.9       , 0.33333333, 0.30769231, 0.53846154,
       0.4       , 0.77777778, 0.11111111, 0.88888889, 0.61538462,
       0.38461538, 0.6       , 0.69230769, 0.76923077, 0.3       ,
       0.23076923, 0.5       , 0.84615385, 0.92307692, 1.        ,
       0.2       , 0.8       , 0.25      , 0.16666667, 0.75      ,
       0.58333333, 0.41666667, 0.83333333, 0.7       , 0.91666667,
       0.07692308, 0.        , 0.1       , 0.15384615])

In [24]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))/100
        return x
    except:
        return np.nan
fbs['foreign_spot'] = fbs['foreign_spot'].apply(lambda x: clean_sup(str(x)))
fbs['foreign_spot'].unique()


array([ nan, 0.02, 0.07, 0.04, 0.03, 0.18, 0.01, 0.14, 0.17, 0.2 , 0.33,
       0.32, 0.06, 0.05, 0.  , 0.23, 0.25, 0.1 , 0.12, 0.09, 0.16, 0.08,
       1.  , 0.29, 0.26, 0.11, 0.13, 0.27, 0.41, 0.19, 0.68, 0.15])

In [25]:

def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))
        return x
    except:
        return np.nan
fbs['sup_doz'] = fbs['sup_doz'].apply(lambda x: clean_sup(str(x)))
fbs['sup_doz'].unique()

array([nan, 2.4, 2.5, 2.2, 2.7, 1.5, 2.1, 1.9, 2.9, 2.3, 2. , 3.3, 1.6,
       1.8, 1.7, 2.6, 3.2, 3.1, 1.4, 3.6, 2.8, 3. , 1.2, 1.3, 3.5])

In [26]:
for zahl in ['sup_in_studies','curriculum',	'students_orga',	'exams',	'research_conn',	'offer_joborientation',	'supp_exchange',	'faculties',	'bib',	'it_infrastructure',	'grade_overall']:

    fbs[zahl] = fbs[zahl].apply(lambda x: clean_sup(str(x)))
    

In [27]:
fbs.head()

id_uni   id_fak  \
0  2       30546     
1  2       1200001   
2  2       420102    
3  2       600799    
4  2       200001    

                                                                     name_fb  \
0  Philologische Fakultät an der Uni Freiburg                                  
1  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       
2  Fakultät für Biologie an der Uni Freiburg                                   
3  Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg   
4  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       

       city                 street_nr    plz  total_stud  total_stud_ma  \
0  Freiburg  Rempartstraße 15          79085  470         130             
1  Freiburg  Albertstr. 21             79104  90          <NA>            
2  Freiburg  Schänzlestraße 1          79104  1260        <NA>            
3  Freiburg  Platz der Alten Synagoge  79098  530         160             
4  Freiburg  Albertstr. 21             79104  940         <NA>            

   support_start  tframe_grad_ba  tframe_grad_ma       lon        lat  int_ba  \
0 NaN             0.733           0.267           7.847936  47.998253 NaN       
1 NaN            NaN              0.537           7.847936  47.998253 NaN       
2  0.785714       0.882           0.549           7.847936  47.998253 NaN       
3 NaN             0.831           0.435           7.847936  47.998253 NaN       
4  0.500000       0.789          NaN              7.847936  47.998253 NaN       

   int_ma  foreign_spot  sup_doz  sup_in_studies  curriculum  students_orga  \
0 NaN     NaN           NaN      NaN             NaN         NaN              
1 NaN     NaN           NaN      NaN             NaN         NaN              
2 NaN     NaN            2.4     NaN              2.5         1.6             
3 NaN     NaN           NaN      NaN             NaN         NaN              
4 NaN     NaN           NaN      NaN             NaN         NaN              

   exams  research_conn  offer_joborientation  supp_exchange  faculties  bib  \
0 NaN    NaN            NaN                   NaN            NaN        NaN    
1 NaN    NaN            NaN                   NaN            NaN        NaN    
2  2.4    2.1           NaN                    2.4            1.7        1.8   
3 NaN    NaN            NaN                   NaN            NaN        NaN    
4 NaN    NaN            NaN                   NaN            NaN        NaN    

   it_infrastructure  grade_overall total_students_la  \
0 NaN                NaN             330 *              
1 NaN                NaN             NaN                
2  2.3                2.2            263                
3 NaN                NaN             NaN                
4 NaN                 2.5            NaN                

                                                                          la_studies  
0  keine Angaben                                                                      
1  NaN                                                                                
2  Abschlüsse: Zwei-Fach-Bachelor, Master of Education; Lehramtstypen: LA Sek II/Gym  
3  NaN                                                                                
4  NaN

In [28]:
def clean_sup(x):
    try:
        x = str(x).replace(' *','').replace('.','')
        x = int(x)
        return x
    except:
        return np.nan

fbs['total_students_la'] = fbs['total_students_la'].apply(lambda x: clean_sup(str(x)))


fbs['total_students_la'].unique()

array([ 330.,   nan,  263.,  214.,  610.,  224.,  191.,  910.,  216.,
        331.,  940.,  338.,  284.,   69.,  150.,  105.,  101.,  520.,
        151.,  460.,  240.,  340.,  320.,  540.,  500.,  303.,  960.,
        326.,  313., 1010.,  159., 8320., 2931.,  480.,  267.,  760.,
        100.,  256.,  234.,  170.,  288.,  155.,  190.,  370.,   35.,
        450.,  699.,  317.,  920.,  964., 1440.,  271.,  182.,  950.,
        653., 1130., 2462., 1050.,  427., 1120.,  687.,  690., 1220.,
        430.,  186.,  253.,  623.,  580.,  474.,  800.,  433.,  277.,
        169., 1420., 1034.,   10.,  158.,  300.,  680.,  443.,  810.,
        761., 1030.,  842., 2690., 1869.,  758.,  980.,  192.,  207.,
       1100.,   95.,  125.,  470.,   66.,  290.,  416.,  440.,  348.,
        650., 1300.,   49.,  160.,  239.,  193.,  180.,  336.,  394.,
        720., 1032.,  257.,  154.,  951.,  230.,  362.,  360., 1256.,
        700.,  130.,  799., 2700., 1198.,  247.,  426.,  640.,  728.,
        422.,  250.,

In [29]:
fbs['la_studies'].nunique()

102

In [30]:
fbs.drop('la_studies', axis = 1, inplace = True)

In [31]:
fbs.to_csv('./data/fbs_cleaned.csv')

In [36]:
fbs.columns

Index(['id_uni', 'id_fak', 'name_fb', 'city', 'street_nr', 'plz', 'total_stud',
       'total_stud_ma', 'support_start', 'tframe_grad_ba', 'tframe_grad_ma',
       'lon', 'lat', 'int_ba', 'int_ma', 'foreign_spot', 'sup_doz',
       'sup_in_studies', 'curriculum', 'students_orga', 'exams',
       'research_conn', 'offer_joborientation', 'supp_exchange', 'faculties',
       'bib', 'it_infrastructure', 'grade_overall', 'total_students_la'],
      dtype='object')

In [38]:
rel_ba = (fbs['total_stud'].mean()-fbs['total_stud_ma'].mean())/(fbs['total_stud'].mean())
rel_ma = 1 - rel_ba
print(rel_ba)
print(rel_ma)

0.7731790219665312
0.2268209780334688


In [49]:
fbs['total_stud'].isnull().value_counts()
#fbs['total_stud'].count()

False    1724
True     527 
Name: total_stud, dtype: int64

In [75]:
def definer_mg(x):
    x = x.lower() 
    if  x.find('medi') > -1 or x.find('medi') > -1 or x.find('gesund') > -1 or x.find('pharma') > -1 or x.find('spo') > -1 or x.find('psy') > -1  or x.find('lebe') > -1 or x.find('human') > -1 or x.find('leben') > -1:
        return 1
    else:
        return 0
def definer_mn(x):
    x = x.lower() 
    if x.find('math') > -1 or x.find('phy') > -1 or x.find('tech') > -1 or x.find('chem') > -1 or x.find('bio') > -1 or x.find('mint') > -1 or x.find('nat') > -1 or x.find('geo') > -1:
        return 1
    else:
        return 0
def definer_rws(x): 
    x = x.lower() 
    if x.find('wirt') > -1 or x.find('sozial') > -1 or x.find('recht') > -1  or x.find('jur') > -1  or x.find('betr') > -1 or x.find('gese') > -1 or x.find('pol') > -1  or x.find('ver') > -1 or x.find('geist') > -1 or x.find('volksw') > -1 or x.find('bwl') > -1:
        return 1
    else:
        return 0
def definer_sk(x):
    x = x.lower()  
    if x.find('eng') > -1 or x.find('phil') > -1 or x.find('phil') > -1 or x.find('fran') > -1 or x.find('amer') > -1 or x.find('angl') > -1  or x.find('jap') > -1 or x.find('asia') > -1 or x.find('ling') > -1 or x.find('kult') > -1 or x.find('lit') > -1:
        return 1
    else:
        return 0
def definer_ii(x):
    x = x.lower() 
    if x.find('ing') > -1 or x.find('info') > -1 or x.find('tech') > -1 or x.find('masch') > -1 or x.find('elektro') > -1 or x.find('arch') > -1 or x.find('fran') > -1 or x.find('bau') > -1 or x.find('luft') > -1 or x.find('raum') > -1 :
        return 1
    else:
        return 0



In [76]:
fbs['med_d'] = fbs['name_fb'].apply(lambda x: definer_mg(x))
fbs['nat_d'] = fbs['name_fb'].apply(lambda x: definer_mn(x))
fbs['rws_d'] = fbs['name_fb'].apply(lambda x: definer_rws(x))
fbs['spr_d'] = fbs['name_fb'].apply(lambda x: definer_sk(x))
fbs['ing_d'] = fbs['name_fb'].apply(lambda x: definer_ii(x))
fbs.head()

id_uni   id_fak  \
0  2       30546     
1  2       1200001   
2  2       420102    
3  2       600799    
4  2       200001    

                                                                     name_fb  \
0  Philologische Fakultät an der Uni Freiburg                                  
1  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       
2  Fakultät für Biologie an der Uni Freiburg                                   
3  Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg   
4  Fakultät für Chemie und Pharmazie an der Uni Freiburg                       

       city                 street_nr    plz  total_stud  total_stud_ma  \
0  Freiburg  Rempartstraße 15          79085  470         130             
1  Freiburg  Albertstr. 21             79104  90          <NA>            
2  Freiburg  Schänzlestraße 1          79104  1260        <NA>            
3  Freiburg  Platz der Alten Synagoge  79098  530         160             
4  Freiburg  Albertstr. 21             79104  940         <NA>            

   support_start  tframe_grad_ba  tframe_grad_ma       lon        lat  int_ba  \
0 NaN             0.733           0.267           7.847936  47.998253 NaN       
1 NaN            NaN              0.537           7.847936  47.998253 NaN       
2  0.785714       0.882           0.549           7.847936  47.998253 NaN       
3 NaN             0.831           0.435           7.847936  47.998253 NaN       
4  0.500000       0.789          NaN              7.847936  47.998253 NaN       

   int_ma  foreign_spot  sup_doz  sup_in_studies  curriculum  students_orga  \
0 NaN     NaN           NaN      NaN             NaN         NaN              
1 NaN     NaN           NaN      NaN             NaN         NaN              
2 NaN     NaN            2.4     NaN              2.5         1.6             
3 NaN     NaN           NaN      NaN             NaN         NaN              
4 NaN     NaN           NaN      NaN             NaN         NaN              

   exams  research_conn  offer_joborientation  supp_exchange  faculties  bib  \
0 NaN    NaN            NaN                   NaN            NaN        NaN    
1 NaN    NaN            NaN                   NaN            NaN        NaN    
2  2.4    2.1           NaN                    2.4            1.7        1.8   
3 NaN    NaN            NaN                   NaN            NaN        NaN    
4 NaN    NaN            NaN                   NaN            NaN        NaN    

   it_infrastructure  grade_overall  total_students_la total_students_ma_appr  \
0 NaN                NaN             330.0              340                     
1 NaN                NaN            NaN                 <NA>                    
2  2.3                2.2            263.0              <NA>                    
3 NaN                NaN            NaN                 370                     
4 NaN                 2.5           NaN                 <NA>                    

   med_d  nat_d  rws_d  spr_d  ing_d  sum  
0  0      0      0      1      0      0    
1  1      1      0      1      0      0    
2  0      1      0      1      0      0    
3  0      0      1      1      0      0    
4  1      1      0      1      0      0

In [81]:
fbs['sonst'] = fbs[['med_d','nat_d','rws_d','spr_d','ing_d']].apply(lambda x: 0 if x.med_d + x.nat_d + x.rws_d + x.spr_d + x.ing_d > 0 else 1, axis = 1)
fbs['sonst'].value_counts()
fbs[fbs['sonst']==1]

id_uni  id_fak  \
442   60      30056    
579   76      30241    
581   76      30237    
591   76      430606   
944   126     30197    
974   132     30620    
977   132     30621    
980   132     30297    
981   132     400166   
983   132     400168   
984   132     604149   
985   132     100151   
986   132     30299    
987   132     440062   
1236  176     30534    
1241  176     604222   
1325  272     604374   
1671  440     100232   
1673  440     400401   
1677  440     100322   
1678  440     11060    
1750  454     100025   
1755  454     410534   
1890  500     7017     
1965  522     420167   
2109  576     604416   
2110  576     500468   
2115  576     500468   
2118  576     604415   
2146  628     410248   
2147  628     440194   
2148  628     603107   
2165  664     500563   
2166  664     600664   
2167  664     500565   
2168  664     500564   
2169  664     500638   
2170  664     602106   
2202  754     600751   
2206  762     602157   
2224  778     604183   

                                                                                name_fb  \
442   Fachbereich 12: Erziehungs- und Bildungswissenschaften an der Uni Bremen            
579   Fachbereich 21: Erziehungswissenschaften an der Uni Marburg                         
581   Fachbereich 09: Germanistik und Kunstwissenschaften an der Uni Marburg              
591   Fachbereich 21 Erziehungswissenschaften an der Uni Marburg                          
944   Fachbereich 1: Bildungswissenschaften (Koblenz) an der Uni Kobl.-Land./Koblenz      
974   Fachbereich II an der Uni Trier                                                     
977   Fachbereich I an der Uni Trier                                                      
980   Fachbereich II an der Uni Trier                                                     
981   Fachbereich IV an der Uni Trier                                                     
983   Fachbereich IV an der Uni Trier                                                     
984   Fachbereich I an der Uni Trier                                                      
985   Fachbereich III an der Uni Trier                                                    
986   Fachbereich I an der Uni Trier                                                      
987   Fachbereich II an der Uni Trier                                                     
1236  Fachbereich Bildungswissenschaften an der Uni Duisburg-Essen/Essen                  
1241  Fachbereich Bildungswissenschaften an der Uni Duisburg-Essen/Essen                  
1325  Fachbereich Bildungswissenschaft an der Alanus HS/Alfter (priv.)                    
1671  Fachbereich 2 an der HS Bremerhaven                                                 
1673  Fachbereich 2 an der HS Bremerhaven                                                 
1677  Fachbereich 2 an der HS Bremerhaven                                                 
1678  Fachbereich 2 an der HS Bremerhaven                                                 
1750  Wiesbaden Business School an der HS RheinMain/Wiesbaden                             
1755  Wiesbaden Business School an der HS RheinMain/Wiesbaden                             
1890  Peter Behrens School of Arts an der HS Düsseldorf                                   
1965  Fachbereich II: Heilpädagogik und Pflege an der EvHS Rheinland/Bochum               
2109  Fachbereich SciTec an der EAH Jena                                                  
2110  Fachbereich SciTec an der EAH Jena                                                  
2115  Fachbereich SciTec an der EAH Jena                                                  
2118  Fachbereich SciTec an der EAH Jena                                                  
2146  Fachbereich Handels- und Logistikmanagement an der EuFH Rhein/Erft, Brühl (priv.)   
2147  Fachbereich General Management an der EuFH Rhein/Erft, Brühl (priv.)                
2148  Business School an der EuFH Rhein/Erft, Brühl (priv.)                          

In [80]:
fbs.drop('sum', axis = 1, inplace = True)